name: 'Hello World'
description: 'Saying hello to the world!'
author: 'Colby Fayock <hello@colbyfayock.com>'

runs:
  using: 'node12'
  main: 'index.js'
inputs:
  commit-count:  # id of input
    description: 'commit input'
    required: true
    default: '4'
    
  LabelName: # id of input
    description: 'label name input'
    required: true
    default: 'LargePR'
  Comments: # id of input
    description: 'comment'
    required: true
    default: 'The PR should have less than 10 commits'
  token: #id of input
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  PR_Number:
    description: 'Pull request number'
    required: true
    default: '3'

outputs:
  CommitsCounts: # id of output
    description: 'The time we greeted you'
  labelname:
    description: 'label name'
  comments:
    description: 'commants description'
  github_token:
    description: 'github token'
  pr_number:
    description: ;pull request number'
